name 'starof_customers'
maintainer 'Balkrishna Pandey'
maintainer_email 'sachit.nep@gmail.com'
license 'all_rights'
description 'Installs/Configures starof_customers'
long_description 'Installs/Configures starof_customers'
version '0.3.4'

depends 'apt', '~> 2.9.1'
depends 'httpd', '~> 0.3.0'
depends 'firewall', '~> 1.5.0'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'mysql', '~> 6.1.2'
depends 'database', '~> 4.0.3'
